services:
  ittp.usersmanagement.api:
    image: ${DOCKER_REGISTRY-}ittpusersmanagementapi
    build:
      context: .
      dockerfile: ITTP.UsersManagement.API/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
  ittp.usersmanagement.db:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_DB: "usersmanagement.db"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "admin"
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432" 
volumes:
    postgres-data: